### ISSUE TITLE
作者你好，请问测试和训练结果什么时候出来？结果表现的如何？

### ISSUE THREAD

**Issue by liuzhuang1024** [MhLiao/MaskTextSpotter#1]

**Comment by MhLiao** [comment]
训练好的模型已经放出来了，该模型的表现应当于论文中结果一致。weighted edit distance和evaluation部分的代码还在整理之中。

**Comment by zmywly8866** [comment]
@MhLiao 你们学校在github上有群组吗？想看你们实验室其它的开源项目，怎样可以找到？

**Comment by MhLiao** [comment]
@zmywly8866 目前还没有。可以针对特定的文章搜索。
