### ISSUE TITLE
[ pretrain ] doesn't save the best model

### ISSUE THREAD

**Issue by ghost** [MhLiao/MaskTextSpotter#10]
Hi,
When I pretrain using icdar 2013, while training the **best model** is not saved.
Instead Pretrain is using the default [`CHECKPOINT_PERIOD`](https://github.com/MhLiao/MaskTextSpotter/blob/master/maskrcnn_benchmark/config/defaults.py#L266) which is 2500.
Pretrain should constantly save the best model.

**Comment by MhLiao** [comment]
@deepseek The evaluation hasn't been integrated into the training code. Thus, we just save the model by the checkpoint period.
