### ISSUE TITLE
Adding more control parameters for inference

### ISSUE THREAD

**Issue by ghost** [MhLiao/MaskTextSpotter#12]
.

**Comment by deepseek** [comment]
@MhLiao this is very important, to only detect the text.
without recognition

**Comment by MhLiao** [comment]
@deepseek  Sorry for the late response. I think you should modify some code in the text_inference.py to ignore some values that do not exist when the recognition is off, e.g. char_predictions.

**Comment by deepseek** [comment]
@MhLiao which values exactly.
update the `text_inference.py` so it would skip the missing ones.

**Comment by deepseek** [comment]
@MhLiao 
I consulted 2 experts in the field, and they told me that it might not be possible to remove the text recognition part from the inference script.

@MhLiao Can you reply back, can you remove the text recognition part from the inference script.

**Comment by deepseek** [comment]
@MhLiao I tried many times, but I still can make MaskTextSpotter inference without text recognition.

**Comment by deepseek** [comment]
it seems to me that the network does both detection and recognition at the same time, (i.e. in final layers)
