### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by ustczhouyu** [MhLiao/MaskTextSpotter#19]
@MhLiao Thank you for sharing the code. When I use one  k80 (11G) to train the model, I need to set IMS_PER_BATCH: 1, otherwise CUDA out of memory. I want to know which parameters in finetune.yaml should be modified so that  batch_size can be bigger without degrading performance.
I look forward to your reply.

**Comment by MhLiao** [comment]
@ustczhouyu I think the best option is using more GPUs to train the model. I have not tried to train it with a single GPU thus I am not sure about the performance. Except for the image batch size, there are [RoI batch size](https://github.com/MhLiao/MaskTextSpotter/blob/d63ce1c8d3bd22391a855586e33519e2ce20147b/configs/finetune.yaml#L17) and [mask RoI batch size](https://github.com/MhLiao/MaskTextSpotter/blob/d63ce1c8d3bd22391a855586e33519e2ce20147b/configs/finetune.yaml#L40) which are related to the memory usage.

**Comment by sno6** [comment]
@ustczhouyu did you ever manage to resolve this? I'm hitting the same issue on a single K80 and can't figure out why a batch size of 8 would max out the GPU.
