### ISSUE TITLE
Training datasets format

### ISSUE THREAD

**Issue by donglinAI** [MhLiao/MaskTextSpotter#2]
@MhLiao Hi, Could you tell me the format of training datasets such as ICDAR13,15,syn, when finetuning the model. And the training process need the ground truth of the every character in one word text? Thank you!

**Comment by MhLiao** [comment]
@donglin8506 I have given the download links of ICDAR2013 and ICDAR2015 as examples. If the dataset has the character-level annotations, you can use them. It doesn't matter if some datasets have no character-level annotations. You can choose to use character-level annotations [here](https://github.com/MhLiao/MaskTextSpotter/blob/73052da777502985aa5e9edde45502bb837e579a/maskrcnn_benchmark/config/paths_catalog.py#L85).

**Comment by donglinAI** [comment]
Thank you very much! Best regards!
