### ISSUE TITLE
which python version is needed?And I meet the issue of "cuda out of memery" using single gpu GTX2080Ti(11G), what GPU did u use?

### ISSUE THREAD

**Issue by Rosesor** [MhLiao/MaskTextSpotter#21]

**Comment by MhLiao** [comment]
@Rosesor I test the code with python3.7. I am not sure whether it is compatible with other versions. I use Titan Xp GPUs.  If you suffer `Cuda out of memory` in the training period you should reduce the [batch size](https://github.com/MhLiao/MaskTextSpotter/blob/d63ce1c8d3bd22391a855586e33519e2ce20147b/configs/finetune.yaml#L67) or use more GPUs. In the inference period, a single GPU is OK.

**Comment by Rosesor** [comment]
> @Rosesor I test the code with python3.7. I am not sure whether it is compatible with other versions. I use Titan Xp GPUs. If you suffer `Cuda out of memory` in the training period you should reduce the [batch size](https://github.com/MhLiao/MaskTextSpotter/blob/d63ce1c8d3bd22391a855586e33519e2ce20147b/configs/finetune.yaml#L67) or use more GPUs. In the inference period, a single GPU is OK.

Thanks!
