### ISSUE TITLE
Configuration to better detect text-lines

### ISSUE THREAD

**Issue by ghost** [MhLiao/MaskTextSpotter#26]
@MhLiao 
What configuration do you recommend to better detect text-lines?

**Comment by MhLiao** [comment]
@deepseek Maybe add some [anchors of extreme aspect ratios](https://github.com/MhLiao/MaskTextSpotter/blob/d63ce1c8d3bd22391a855586e33519e2ce20147b/maskrcnn_benchmark/config/defaults.py#L119) will be helpful.

**Comment by ghost** [comment]
@MhLiao 
PMTD uses these ratios `(0.17, 0.44, 1.13, 2.90, 7.46)`

Other than `ASPECT_RATIOS` is there anything else you'd recommend?

**Comment by MhLiao** [comment]
@deepseek Another suggestion is adding some tricks to enlarge the receptive field in the backbone, such as deformable convolution v2.

**Comment by ghost** [comment]
thanks
