### ISSUE TITLE
Detectron2

### ISSUE THREAD

**Issue by ghost** [MhLiao/MaskTextSpotter#27]
@MhLiao @lvpengyuan Detectron2 was just released,
Do you have plans to upgrade MasTextSpotter to Detectron2?

**Comment by MhLiao** [comment]
@deepseek No such plan yet. I will try to complete this repo firstly.

**Comment by ghost** [comment]
thanks

**Comment by cbasavaraj** [comment]
Hi @MhLiao, I think integrating this repo as a project under the detectron2 framework would be very useful. Detectron2 support Faster-RCNN as well as Mask-RCNN. It is super popular and your work would become accessible to all the people using D2. Thanks!
