### ISSUE TITLE
多语种训练问题

### ISSUE THREAD

**Issue by rkshuai** [MhLiao/MaskTextSpotter#29]
请问对于mlt这种没有character-level的标注，不会像fots算法一样，在前期训练时检测不准确从而导致识别出现问题的情况吗？训练mlt是在预训练模型上微调的吗？

**Comment by MhLiao** [comment]
@rkshuai MLT的训练我们参考的[E2E-MLT](https://github.com/MichalBusta/E2E-MLT), 使用了他提供的合成数据集预训练。我觉得这种问题是存在的，但是我们的实验不需要分阶段训练检测和识别也是可以的。
