### ISSUE TITLE
Training stuck

### ISSUE THREAD

**Issue by hhhoushiyu** [MhLiao/MaskTextSpotter#39]
Thank you for your excellent work!
I got stuck trying to train for unknown reasons.

`2019-12-05 16:06:33,983 maskrcnn_benchmark.trainer INFO: Start training
tensor(0, device='cuda:0')
chars_boxes.shape:  0`

Volatile GPU-Util is 0%
Please tell me what's wrong with me.Thank you very much

**Comment by sno6** [comment]
Hello @hhhoushiyu I am stuck with a similar issue. How did you resolve this?

**Comment by TriplePool** [comment]
@sno6 I met the same issue, have you handled it?

**Comment by sno6** [comment]
Possibly.. I’ve noticed that it only happens when using character level bounding boxes, as in my case. Are you using word level or char level labels? @TriplePool

**Comment by TriplePool** [comment]
> Possibly.. I’ve noticed that it only happens when using character level bounding boxes, as in my case. Are you using word level or char level labels? @TriplePool

Yes, I think there is something wrong with icdar2013 dataset.  After I removed icdar2013 from training config, the training process was stable.

**Comment by sno6** [comment]
Yep, I've got two custom datasets I'm running and whenever I turn on character bounding boxes it doesn't want to train. That should narrow it down enough, I'll have a deeper look tonight and see if there's an easy fix.

**Comment by sno6** [comment]
For anyone else who comes across this issue.. 

1. Make sure that there aren't any old training processes still running. Sometimes If I canceled out of training and then restarted it would hang until the first process had been killed.

2. Make sure that your character level label files are correct. I've put an example of a label file and a custom dataset file here: https://gist.github.com/sno6/aa7891abce4ecbacb9beeab8fa2ccf94
