### ISSUE TITLE
只训练检测分支需要怎么做

### ISSUE THREAD

**Issue by WenmuZhou** [MhLiao/MaskTextSpotter#4]

**Comment by MhLiao** [comment]
我会在之后的版本里增加一个控制的flag。现阶段你可以直接设置`MODEL.CHAR_MASK_ON`和`SEQUENCE.SEQ_ON`为False

**Comment by WenmuZhou** [comment]
ths

**Comment by hhhoushiyu** [comment]
> 我会在之后的版本里增加一个控制的flag。现阶段你可以直接设置`MODEL.CHAR_MASK_ON`和`SEQUENCE.SEQ_ON`为False

我这样设置之后，报错`AttributeError: 'SeqCharMaskRCNNC4Predictor' object has no attribute 'seq'`
我该怎么做？
谢谢
