### ISSUE TITLE
Vertical Text

### ISSUE THREAD

**Issue by sno6** [MhLiao/MaskTextSpotter#44]
Will this project work with vertical text if given a vertical text dataset? or would there need to be more changes to get it to work.

**Comment by sno6** [comment]
To answer myself, yes quite well.

![5](https://user-images.githubusercontent.com/8223143/75740263-1184fa00-5d6c-11ea-99db-d42480d9e9f3.png)

![6](https://user-images.githubusercontent.com/8223143/75740281-1a75cb80-5d6c-11ea-81f5-df6e3be5b1d8.jpg)

**Comment by ghost** [comment]
@sno6 but cat it detect long text-lines[ dataset sample](https://drive.google.com/file/d/18Y1Yqg5mBj_b_J2DegIIJBGQ5-PxXYy1/view?usp=sharing)
this is in icdar2015 format annotation

**Comment by sno6** [comment]
Sorry @deepseek this model was trained on a very different dataset for a very different problem. You're going to have to train on icdar2015 yourself to find that out.
