### ISSUE TITLE
中文识别效果问题

### ISSUE THREAD

**Issue by ivoxx** [MhLiao/MaskTextSpotter#52]
我用Mask TextSpotter训练了一个4000类的中文模型(用了4万行私有弯曲中文文本数据），发现序列识别效果还行，字符分割效果较差，是不是因为中文字符的shrink操作给字符分割带来不好的影响，或者是类别多难度大？这个现象是不是正常的？

**Comment by yyr6661** [comment]
可以请教一下使用中文数据训练具体需要做哪些修改吗？

**Comment by mxin262** [comment]
@ivoxx 你好，我和你恰恰相反，我的字符分割的效果还行，但是中文识别的效果较差，请问你是对识别那边是做了什么处理吗？

**Comment by oszn** [comment]
有无开源博客来讲讲修改的方法。

**Comment by oszn** [comment]
> @ivoxx 你好，我和你恰恰相反，我的字符分割的效果还行，但是中文识别的效果较差，请问你是对识别那边是做了什么处理吗？

请问这个模型在中文上真的可行嘛

**Comment by gtb1551050818** [comment]
> > @ivoxx 你好，我和你恰恰相反，我的字符分割的效果还行，但是中文识别的效果较差，请问你是对识别那边是做了什么处理吗？
> 
> 请问这个模型在中文上真的可行嘛



> 有无开源博客来讲讲修改的方法。

请问你知道使用中文数据集训练需要怎么修改了嘛
