### ISSUE TITLE
运行sh test.sh提示文件不存在

### ISSUE THREAD

**Issue by Laura1021678398** [MhLiao/MaskTextSpotter#9]
提示错误：`FileNotFoundError: [Errno 2] No such file or directory: 'datasets/icdar2013/test_gts/gt_img_1.txt'`

**Comment by ghost** [comment]
@Laura1021678398 you need to download the [dataset](https://github.com/MhLiao/MaskTextSpotter#datasets) and place it in the `datasets` folder

**Comment by Laura1021678398** [comment]
@deepseek  I have placed icdar2013 in the `datasets` folder, but there have no `test_gts` folder in the icdar2013

**Comment by MhLiao** [comment]
@Laura1021678398 You can try to delete or comment this [line](https://github.com/MhLiao/MaskTextSpotter/blob/5239eee3fbc3f04b20dc0bce818d40364f50c1fa/maskrcnn_benchmark/config/paths_catalog.py#L31)

**Comment by foocker** [comment]
> 
> 
> @Laura1021678398 You can try to delete or comment this [line](https://github.com/MhLiao/MaskTextSpotter/blob/5239eee3fbc3f04b20dc0bce818d40364f50c1fa/maskrcnn_benchmark/config/paths_catalog.py#L31)
@MhLiao 
in icdar.py line 50: if self.vis:
should add "and target", when test, target is None.

**Comment by Laura1021678398** [comment]
万分感谢！！！

**Comment by ghost** [comment]
Or you can simply change line [87 from paths_catalog.py](https://github.com/MhLiao/MaskTextSpotter/blob/master/maskrcnn_benchmark/config/paths_catalog.py#L87) to `gts_dir=None`
